# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_item',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_user',
        ),
        migrations.AddField(
            model_name='item',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist_list', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_added', to='login_app.User'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
